name: Atualizar elementais

"on":
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Testar workflow
        run: echo "Workflow funcionando"
